# Form implementation generated from reading ui file '.\\templates\\dlgAbout.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgAbout(object):
    def setupUi(self, dlgAbout):
        dlgAbout.setObjectName("dlgAbout")
        dlgAbout.resize(407, 300)
        dlgAbout.setModal(True)
        self.frame = QtWidgets.QFrame(parent=dlgAbout)
        self.frame.setGeometry(QtCore.QRect(0, 0, 411, 301))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.lblNombreApp = QtWidgets.QLabel(parent=self.frame)
        self.lblNombreApp.setGeometry(QtCore.QRect(120, 20, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lblNombreApp.setFont(font)
        self.lblNombreApp.setObjectName("lblNombreApp")
        self.lblVersion = QtWidgets.QLabel(parent=self.frame)
        self.lblVersion.setGeometry(QtCore.QRect(120, 60, 121, 21))
        self.lblVersion.setObjectName("lblVersion")
        self.lbl_Info = QtWidgets.QLabel(parent=self.frame)
        self.lbl_Info.setGeometry(QtCore.QRect(120, 80, 261, 61))
        self.lbl_Info.setScaledContents(False)
        self.lbl_Info.setWordWrap(True)
        self.lbl_Info.setIndent(0)
        self.lbl_Info.setOpenExternalLinks(False)
        self.lbl_Info.setObjectName("lbl_Info")
        self.lbl_Info_2 = QtWidgets.QLabel(parent=self.frame)
        self.lbl_Info_2.setGeometry(QtCore.QRect(120, 130, 261, 41))
        self.lbl_Info_2.setScaledContents(False)
        self.lbl_Info_2.setWordWrap(True)
        self.lbl_Info_2.setIndent(0)
        self.lbl_Info_2.setOpenExternalLinks(False)
        self.lbl_Info_2.setObjectName("lbl_Info_2")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(10, 30, 71, 71))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".\\\\templates\\../img/icono.ico"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(120, 160, 181, 31))
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByKeyboard|QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextBrowserInteraction|QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_2.setObjectName("label_2")
        self.btnSalir = QtWidgets.QPushButton(parent=self.frame)
        self.btnSalir.setGeometry(QtCore.QRect(310, 250, 75, 23))
        self.btnSalir.setObjectName("btnSalir")

        self.retranslateUi(dlgAbout)
        QtCore.QMetaObject.connectSlotsByName(dlgAbout)

    def retranslateUi(self, dlgAbout):
        _translate = QtCore.QCoreApplication.translate
        dlgAbout.setWindowTitle(_translate("dlgAbout", "Dialog"))
        self.lblNombreApp.setText(_translate("dlgAbout", "INMO TEIS (DE JOEL FIGUEIRIDO)"))
        self.lblVersion.setText(_translate("dlgAbout", "Version 0.1.1"))
        self.lbl_Info.setText(_translate("dlgAbout", "Aplicacion para controlar la gestion de propiedades y clientes de las propiedades del area metropolitana de vigo y alrededores"))
        self.lbl_Info_2.setText(_translate("dlgAbout", "Para mas informacion sobre el funcionamiento consultar:"))
        self.label_2.setText(_translate("dlgAbout", "https://github.com/joeelfgrd"))
        self.btnSalir.setText(_translate("dlgAbout", "Cerrar"))
