# Form implementation generated from reading ui file '.\\templates\\dlgBuscarProp.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgInformeProp(object):
    def setupUi(self, dlgInformeProp):
        dlgInformeProp.setObjectName("dlgInformeProp")
        dlgInformeProp.resize(350, 200)
        self.layoutWidget = QtWidgets.QWidget(parent=dlgInformeProp)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 40, 301, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        self.label.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cmbInformeMuniProp = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.cmbInformeMuniProp.setMinimumSize(QtCore.QSize(150, 0))
        self.cmbInformeMuniProp.setEditable(True)
        self.cmbInformeMuniProp.setObjectName("cmbInformeMuniProp")
        self.horizontalLayout.addWidget(self.cmbInformeMuniProp)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(0, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btnInformeProp = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnInformeProp.setMinimumSize(QtCore.QSize(90, 0))
        self.btnInformeProp.setObjectName("btnInformeProp")
        self.horizontalLayout_2.addWidget(self.btnInformeProp)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(dlgInformeProp)
        QtCore.QMetaObject.connectSlotsByName(dlgInformeProp)

    def retranslateUi(self, dlgInformeProp):
        _translate = QtCore.QCoreApplication.translate
        dlgInformeProp.setWindowTitle(_translate("dlgInformeProp", "Informe Propiedades"))
        self.label.setText(_translate("dlgInformeProp", "Selecciona municipio:"))
        self.btnInformeProp.setText(_translate("dlgInformeProp", "Crear informe"))
