# Form implementation generated from reading ui file '.\\templates\\dlgGestionProp.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlg_TipoProp(object):
    def setupUi(self, dlg_TipoProp):
        dlg_TipoProp.setObjectName("dlg_TipoProp")
        dlg_TipoProp.resize(400, 300)
        dlg_TipoProp.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\\\templates\\../img/logo.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlg_TipoProp.setWindowIcon(icon)
        dlg_TipoProp.setModal(True)
        self.layoutWidget = QtWidgets.QWidget(parent=dlg_TipoProp)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 16, 381, 271))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.layoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(160, 0, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(60, 60))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(".\\\\templates\\../img/logo.ico"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label.setObjectName("label")
        self.lblGestTipoProp = QtWidgets.QLabel(parent=self.frame)
        self.lblGestTipoProp.setGeometry(QtCore.QRect(11, 72, 341, 20))
        self.lblGestTipoProp.setMinimumSize(QtCore.QSize(250, 20))
        self.lblGestTipoProp.setMaximumSize(QtCore.QSize(350, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblGestTipoProp.setFont(font)
        self.lblGestTipoProp.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblGestTipoProp.setObjectName("lblGestTipoProp")
        self.txtGestTipoProp = QtWidgets.QLineEdit(parent=self.frame)
        self.txtGestTipoProp.setGeometry(QtCore.QRect(115, 99, 150, 20))
        self.txtGestTipoProp.setMinimumSize(QtCore.QSize(150, 20))
        self.txtGestTipoProp.setMaximumSize(QtCore.QSize(150, 20))
        self.txtGestTipoProp.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.txtGestTipoProp.setObjectName("txtGestTipoProp")
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnAltaTipoProp = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnAltaTipoProp.setMinimumSize(QtCore.QSize(80, 25))
        self.btnAltaTipoProp.setMaximumSize(QtCore.QSize(80, 25))
        self.btnAltaTipoProp.setObjectName("btnAltaTipoProp")
        self.horizontalLayout.addWidget(self.btnAltaTipoProp)
        self.btnDelTipoProp = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnDelTipoProp.setMinimumSize(QtCore.QSize(80, 25))
        self.btnDelTipoProp.setMaximumSize(QtCore.QSize(80, 25))
        self.btnDelTipoProp.setObjectName("btnDelTipoProp")
        self.horizontalLayout.addWidget(self.btnDelTipoProp)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(dlg_TipoProp)
        QtCore.QMetaObject.connectSlotsByName(dlg_TipoProp)

    def retranslateUi(self, dlg_TipoProp):
        _translate = QtCore.QCoreApplication.translate
        dlg_TipoProp.setWindowTitle(_translate("dlg_TipoProp", "Gestion Tipo Prop"))
        self.lblGestTipoProp.setText(_translate("dlg_TipoProp", "INTRODUZCA EL TIPO DE PROPIEDAD A CREAR O ELIMINAR"))
        self.btnAltaTipoProp.setText(_translate("dlg_TipoProp", "Alta"))
        self.btnDelTipoProp.setText(_translate("dlg_TipoProp", "Eliminar"))
